PyPSA/pypsa-ariadne

environment.yaml
When using several conda environments with the same Python version a strange behaviour may occur: The packages installed via pip are only visible from the environment in which they were first installed. All other environments use these pip-installed packages, but do not list them (via `conda list`). As a consequence its hard to figure out which packages are actually used and in what version. Since all packages used by this repo are available via conda-forge, it would be cleaner not to use pip.
Additionally, restricting linopy <= 0.2.6 fixed a strange bug in solve_network. Apparently @fneum suggested this.
=> Improve environment.yaml

workflow/Snakefile, workflow/scripts/build_wasserstoff_kernnetz.py, workflow/scripts/cluster_wasserstoff_kernnetz.py
review for https://github.com/PyPSA/pypsa-ariadne/pull/6
@JulianGeis looks very good! I have revised the code to:
- use a few Python tricks to make the code cleaner / shorter (have a look at the diff)
- reuse more of the functions from `cluster_gas_network` from PyPSA-Eur
- make mock_snakemake work in pypsa-ariadne
My questions:
1. The build year of the hydrogen pipelines is not considered, right? In `prepare_sector_network`, one could add a line
```py
custom_pipes.query("build_year <= @investment_year", inplace=True)
```
after reading the file so that the minimum capacities and routes depend on the planning horizon.
2. Is the clipping to a minimum pressure of 30 bar and a minimum build year 2030 necessary? Should the latter maybe be a config option?
3. Does it make a difference if you …
=> Review suggestions for `feature_jg`

config/config.yaml, workflow/scripts/_compute_co2_targets_DE.py
The Nationale Emissionsminderungsziele contain all Kyoto gases, Pypsa-eur models only CO2.
We take the non-CO2 Kyoto gases from the ariadne database, and subtract them from the targets. Interestingly this would lead to negative CO2 emissions targets for 2050 -> Does that make sense?
I did not consider any negative emissions from Land Use, Land Use Change and Afforestation yet (as these are not in the Ariadne database). However the KSG mentions negative sector targets for LULUCF. How should these be included? @nworbmot 
This is the script i used to compute the adjusted CO2 targets.
```python
import pyam
import numpy as np
import pandas as pd
pyam.iiasa.set_config(USERNAME, PASSWORD)
model_raw = pyam.read_iiasa("ariadne_intern",
model="Hybrid",
scenario="8Gt_EnSec")
model_df = …
```
=> non-CO2 GHG correction for national CO2 targets

ariadne-data/costs_2020-modifications.csv, ariadne-data/costs_2025-modifications.csv, ariadne-data/costs_2030-modifications.csv, ariadne-data/costs_2035-modifications.csv, ariadne-data/costs_2040-modifications.csv, ariadne-data/costs_2045-modifications.csv, ariadne-data/costs_2050-modifications.csv
Adding cost assumption from the initial price discussion of the [Ariadne Scenarios](https://docs.google.com/document/d/10V6o-1vPECYu5UiEi4alYS8r-CXqZSRKqJkAGKt1N0Y/edit) summarized in the [table](https://cloud.pik-potsdam.de/index.php/f/19528535).
For calculating prices in 2020Eur/MWh the following sources were taken:
- [Euro2020](https://www.bmz.de/de/ministerium/zahlen-fakten/oda-zahlen/hintergrund/dac-umrechnungskurs-35300)
- 1 bbl = 1.6998 MWh for Brent oil
- 1 t = 8.06 MWh for API2 coal
No values for biogas/-mass, lignite and nuclear
=> adding commodity prices for coal, oil, gas from Ariadne assumptions

environment.yaml
Include missing nuclear generation data as it was filtered out by powerplantmatching. Fixed in v0.5.11 in ppl. -> https://github.com/PyPSA/powerplantmatching
=> fix missing nuclear

config/config.yaml
- overwrite config.default.yaml to include nuclear power plants in powerplantmatching
- model nuclear as links and exclude it from being a generator
- adapt query for powerplantmatching to include all plants that have a lifetime until 2019 or longer with DateOut argument
=> Fix nuclear

config/config.yaml, workflow/scripts/modify_prenetwork.py
useful so that electrolysers and H2 pipelines are not built in 2020
could be replaced by max limits constraints
=> add option to specify the year of a technology's first occurrence

environment.yaml
Older pypsa version lead to errors in the optimization of the network
=> Update environment.yaml for latest pypsa version

config/config.yaml, config/scenarios.yaml, environment.yaml, workflow/Snakefile, workflow/scripts/additional_functionality.py, workflow/scripts/build_scenarios.py, workflow/scripts/check_sector_ratios.py, workflow/scripts/modify_prenetwork.py
Creating the `scenarios.yaml` file for the main scenarios in the ariadne project.
- adding limits for the import of electricity, hydrogen and hydrogen derivates
- adding minimum for the installed capacity of electrolysis in Germany
- rule `build_scenarios` reads in the mobility share for land transport and navigation from the specified iiasa scenario
Open ToDos:
=> Setting up main Ariadne scenarios

workflow/scripts/additional_functionality.py
When synfuels are imported to Germany (or any country) the emissions are not accounted for in the national CO2 target. The same applies to the export of synfuels.
This PR adds in `extra_functionality.py` in the function `add_co2limit_country(n, limit_countries, snakemake)` the sum over all import and export of synfuels to/from Germany and subtract/adds multiplied by the emission factor of oil to the national CO2 target.
PR https://github.com/PyPSA/pypsa-ariadne/pull/33 is therefore obsolete. 
at the moment it will only work for "DE". If we want to enable that for any country, the untangling of the oil bus must be flexible as well.
For this look into `modify_prenetwork.py` in https://github.com/PyPSA/pypsa-ariadne/pull/39
=> Import/Export of FT is subtracted/added to the national CO2 target

ariadne-data/costs_2019-modifications.csv, ariadne-data/costs_2020-modifications.csv, ariadne-data/costs_2025-modifications.csv, ariadne-data/costs_2030-modifications.csv, ariadne-data/costs_2035-modifications.csv, ariadne-data/costs_2040-modifications.csv, ariadne-data/costs_2045-modifications.csv, ariadne-data/costs_2050-modifications.csv, config/config.yaml, workflow/Snakefile, workflow/scripts/modify_prenetwork.py
Because of the Covid pandemic, the prices for gas, coal and oil were low because of the decreased demand. Since we are using 2019 demand data from eurostat, the workflow now takes also the prices from 2019 into account.
There are also added heat pump values manually for 2019/2020:
|technology| investment costs|unit|
|---|---|---|
|decentral air-sourced heat pump| 3319| EUR2020/kW_th|
|decentral ground-sourced heat pump| 5340| EUR2020/kW_th|
The Network expansion costs are changed for all `planning_horizons`:
|technology| investment costs|unit|
|---|---|---|
|electricity distribution grid| 3000| EUR2020/kW|
|HVAC overhead|736 | EUR2020/MW/km|
|HVDC inverter pair| 600000| EUR2020/MW|
|HVDC overhead| 1000| EUR2020/MW/km|
|HVDC submarine| 3250| EUR2020/MW/km|
Note that the og table from …
=> Adding NEP21 and cost data for 2019

config/config.yaml, config/scenarios.yaml, workflow/Snakefile, workflow/scripts/build_scenarios.py
This PR provides the configurations for a Trend scenario. Since the [Modellierungsprotokoll](https://docs.google.com/document/d/10V6o-1vPECYu5UiEi4alYS8r-CXqZSRKqJkAGKt1N0Y/edit#heading=h.scs40dks0x32) is quite vague the policy from 2030 is frozen and the following assumptions are made
- the CO2 budget is fixed at the 2030 value for 2035-2050
- the minimum Germna VRE targets are reduced to  75 % of the political targets
-  there is no forced H2 production
- the Kernnetz is not built
- the transport sector is oriented towards the Fraunhofer ReMod model 
- the industry transformation is oriented towards the FORECAST model
Open issues:
Using [DEMOv1.0](https://www.dlr.de/vf/desktopdefault.aspx/tabid-12751/22270_read-50064/) which should be sufficient
=> Trend Scenario 

workflow/Snakefile, workflow/scripts/build_existing_chp_de.py
- Changed snakefile to retrieve and reference data in the new way (storage and resources functions) and adapted the input `plz_mapping` in `build_existing_chp_de.py` accordingly
- Changed the pointer to the changes made in PR of submodule (https://github.com/PyPSA/pypsa-eur/pull/907)
- As a result, backtesting the model for 2020 can yield a more accurate central heat  supply mix. However, this is only the case if the model is additionally restricted to not expand gas boilers (or gas boilers, heat pumps and resistive heaters) in 2020 (as done in `prepare_sector_network.py` in https://github.com/PyPSA/pypsa-eur/pull/907/commits/9219cb9ef39207943bdfc84437fead6ae222348b). Without this restriction the majority of the CHP fleet  (gas, solid biomass) is not dispatched due to their high variable …
=> Add mastr chps

ariadne-data/costs_2019-modifications.csv, ariadne-data/costs_2020-modifications.csv, ariadne-data/costs_2025-modifications.csv, ariadne-data/costs_2030-modifications.csv, ariadne-data/costs_2035-modifications.csv, ariadne-data/costs_2040-modifications.csv, ariadne-data/costs_2045-modifications.csv, ariadne-data/costs_2050-modifications.csv, config/config.yaml, config/scenarios.manual.yaml, workflow/Snakefile, workflow/scripts/modify_cost_data.py, workflow/scripts/modify_prenetwork.py
Adressing https://github.com/PyPSA/pypsa-ariadne/issues/82
This PR adds the `config[costs][NEP]` which can be set to `2021` or `2023`.
Note that the following costs are available:
| Paramter & unit          | NEP 23    | NEP 21 |
|--------------------------|-----------|-----------|
| AC overhead (€/MW/km)    | 1325-1384 | 736    |
| AC underground (€/MW/km) |4711      | 3386   |
| AC submarine (€/MW/km)   | -         | -      |
| DC overhead (€/MW/km)    |  -         | 1000   | 
| DC underground (€/MW/km) |3300-3800 | 3250   |
| DC submarine (€/MW/km)   |  -         | -      |
| DC inverter pair (€/kW)  |-         | 600    |
To convert the cost data to €2020 the following discount rates are used:
inflation rate 0.5% (2020), 3.1% (2021), 7.9% (2022) -> ~0.89686*investment_cost_2023
Since …
=> Add config for NEP2021 and NEP2023 cost data

config/config.yaml, config/scenarios.manual.yaml, workflow/scripts/additional_functionality.py
Since our results showed too much renewable energies in 2020 and 2025, a maximum constraint is introduced.
`config["limits_capacity_max"]` follows the same logic as `config["limits_capacity_min"].
Be aware that defining both upper and lower limits for renewables is possible but might lead to numerical issues.
=> Add max capacity limits for renewable energies in Germany

ariadne-data/costs_2020-modifications.csv, ariadne-data/costs_2025-modifications.csv, config/config.yaml, workflow/Snakefile, workflow/scripts/export_ariadne_variables.py, workflow/scripts/modify_cost_data.py
Adding carbon price in 2020 and 2025 for fossil generators 
- reason: electricity generation from lignite too high and from gas too low in 2020
prices so far:
add ons for specific emissions:
prices now:
difference in electricity generation:
before: 
after:
ariadne plots:
before:
after:
=> add carbon component for coal, gas and oil in 2020 and 2025

workflow/scripts/additional_functionality.py, workflow/scripts/build_scenarios.py, workflow/scripts/modify_prenetwork.py
Adding synthetic fuels, biofuels and ft fuels in navigation as meoh demand. However, this seems to be drastic and leads to 100 % meoh shipping in 2045. Not realistic especially considering the current fleet of ships and their lifetime.
```
sector:
shipping_methanol_share:
2020: 0.0966
2025: 0.1187
2030: 0.1357
2035: 0.175
2040: 0.4558
2045: 1.0
```
In the `unravel_oilbus()` meoh was missing which is needed for industry and shipping. It is following now the same logic as for the oil and added to the boundary condition restricting the import of H2 derivatives (which also missed the import of CH4 on purpose?).
=> Shipping MeOH

config/config.yaml, workflow/Snakefile, workflow/scripts/build_mobility_demand.py, workflow/scripts/build_scenarios.py, workflow/scripts/modify_prenetwork.py
Adressing https://github.com/PyPSA/pypsa-ariadne/issues/102
This PR now takes the road and rail transport demand for hydrogen, electricity and liquids from the Aladin model that also exports to the ariadne databse.
`rule: build_mobility_demand`
The rule reads the demand for electricity, hydrogen and liquids from buses, LDV, rail and trucks. The number of electric vehicles is also retrieved since it determines the V2G and BEV charger capacities.
`rule: modify_prenetwork`
aladin_mobility_demand
This function gets the loads for `[land transport oil, land transport fuel cell, land transport EV]` and overwrites the loads with the values from the Aladin model. Note that the demand is time dependent and therefore, the relative transport demand is built from the `n.loads_t.p_set` dataframe.
=> Transport Demand from Aladin Sector Model

README.md, config/config.public.yaml, config/config.yaml, config/scenarios.public.yaml, workflow/Snakefile, workflow/scripts/build_mobility_demand.py, workflow/scripts/build_scenarios.py, workflow/scripts/modify_industry_demand.py, workflow/scripts/plot_ariadne_variables.py, workflow/scripts/retrieve_ariadne_database.py
This PR prepares the renaming and publication of the repository as PyPSA-DE.
Adressing #69, #56.
=> Preparation for public model Pypsa-DE

config/config.yaml, workflow/Snakefile
Updates the cutout for the weather data to 2019. At the moment this works only with the Cutout shared by Fabian
=> Cutout 2019

ariadne-data/costs_2019-modifications.csv, ariadne-data/costs_2020-modifications.csv, ariadne-data/costs_2025-modifications.csv, ariadne-data/costs_2030-modifications.csv, ariadne-data/costs_2035-modifications.csv, ariadne-data/costs_2040-modifications.csv, ariadne-data/costs_2045-modifications.csv, ariadne-data/costs_2050-modifications.csv, config/config.yaml, config/scenarios.manual.yaml, workflow/scripts/export_ariadne_variables.py
Our offwind connection investment is too low. I updated it to NEP23, however it still seems too low :thinking:. While I increased the input connection investment from ~2000 to ~3000 EUR/km/MW , and while capacities stayed the same, the output costs only increased by ~15%. 
I already fixed an issue in simplify network and double checked the exporter for bugs, but everything seems to be correct :thinking: So why is the costs increase so small? And why are the overall investments so low?
Before:
After:
=> use NEP DC costs for offwind-connection

.github/workflows/validate.yml
Just 1 scenario, no solar thermal.
Still this workflow takes ~30 minutes locally due to all the pre-processing. I guess some further simplifications are necessary for the CI runs, e.g. disabling "estimate_renewables" and using a default cutout. Here i would need some input from @fneum
=> Set up config for CI runs

.git-blame-ignore-revs
Adds `.git-blame-ignore-revs` to ignore pre-commit changes from #156  in `git blame`.
=> Ignore pre-commit changes in `git blame`

workflow/scripts/additional_functionality.py, workflow/scripts/cluster_wasserstoff_kernnetz.py, workflow/scripts/export_ariadne_variables.py
=> minor changes for running single node network

Changelog.md, config/config.yaml, workflow/scripts/additional_functionality.py, workflow/scripts/modify_prenetwork.py
Closes https://github.com/PyPSA/pypsa-ariadne/issues/84
In `additional_functionality` a boundary condition is set by the function `h2_import_limits`.
However, so far only the carrier `H2 pipeline` was considered.
Since there could also be the carriers `H2 pipeline (Kernnetz)` and `H2 pipeline retrofitted`, the query for the incoming and outgoing flow links is changed minor.
The boundary condition works even when Kernnetz and retrofitting is not activated.
There are no changes to the export_araidne_variables rule
The figures did not change since `H2_retrofit` and `Kernnetz` are currently not enabled.
=> Fix hydrogen import boundary condition

config/config.yaml, workflow/scripts/additional_functionality.py
Unify functions `add_{min/max}_capacity` in `additional_functionality.py` to avoid boilerplate code repetition.
Allow this function to limit stores.
Add limits to DE CO2 sequestration based on feasibility constraints.
E.g. since EU target for 2030 is 50 MtCO2/a sequestration in Net Zero Industry Act, limit DE to 10 MtCO2/a, then relax with subsequent years.
For 365H resolution, this limit reduced sequestration in DE in 2030 from 55 to 10 MtCO2, while increasing system costs by 0.3%. The limit in 2045 reduced sequestration in DE from 97 to 80 MtCO2, while increasing system costs by 0.3%.
=>  Limit German CO2 sequestration in each investment year

Changelog.md, config/config.yaml
Closing https://github.com/PyPSA/pypsa-ariadne/issues/176
Please note that I increased the number of nodes. So far 22 nodes translated to 8 nodes for Germany and the rest for the Stromnachbarn.
With adding Italy (and Spain) a total of 5 nodes is needed to model those countries. Italy needs 3 nodes (mainland, Sardinia, Corsica) - Spain needs 2 nodes (mainland, Mallorca).
Workflow runs smoothly and the basenetwork `elec_s_27.nc` looks like this:
=> Adding Italy

config/config.yaml, workflow/Snakefile, workflow/scripts/export_ariadne_variables.py, workflow/scripts/modify_prenetwork.py
- Added BtL, BtL CC and electrobiofuels.
- Bugfix: Connect unsustainable bioliquids to DE bus instead of EU bus
- Refactor: gas_fractions and oil_fractions can both be gotten from the new function _get_fuel_fractions
- oil_fractions now consider bioliquids
Open Todo:
Affect on results:
- Model uses less biomass boilers because BtL better
- Model uses Btl
Before:
After:
Open question: **Should we keep Electrobiofuels?**
=> Add Biomass to Liquid

config/config.yaml, workflow/scripts/export_ariadne_variables.py
The emissions of coke for industry were so far completely assigned to the industry sector.
The production of coke from coal leads to inevitable emissions which are now reported with the variable `Emissions|CO2|Energy|Supply`.
Furthermore, the share of `DRI steel` is adjusted following the [Treibhausprojektion](https://www.umweltbundesamt.de/sites/default/files/medien/11850/publikationen/projektionen_technischer_anhang_0.pdf) by uba.
_only exporter changes_
_only exporter changes_
=> Report coke emissions in energy supply

workflow/scripts/modify_prenetwork.py
In `prepare_sector_network` in `add_storage_and_grids` if `config["sector"]["H2_retrofit"]` the variable `p_nom_extendable` is already multiplied by the `options["H2_retrofit_capacity_per_CH4"]` factor.
This means that multiplying it again in `modify_prenetwork` is not necessary.
**Only bugfix, so none of the points below are done.**
=> Capacity Reduction for Kernnetz not necessary

ariadne-data/costs_2019-modifications.csv, ariadne-data/costs_2020-modifications.csv, ariadne-data/costs_2025-modifications.csv, ariadne-data/costs_2030-modifications.csv, ariadne-data/costs_2035-modifications.csv, ariadne-data/costs_2040-modifications.csv, ariadne-data/costs_2045-modifications.csv, ariadne-data/costs_2050-modifications.csv, config/config.yaml, workflow/scripts/export_ariadne_variables.py
HTLS have higher Ampere, thus updating NEP costs yet again.
For NEP 2021
HVAC:
Neubau = 2.5M€/km, HTLS Addon = 0.2M€/km , Ampere = 4000, Volts = 380
2.7 M/km / (380k * 4k * sqrt(3) * 2) = 513 € / MWkm -> Inflation: 1.005: 510
offwind-ac: Ampere = 1000, Volts = 220
For NEP 2023
HVAC:
Neubau = 4.5M€/km, rest stays the same -> 893€/km -> Inflation: 1.108 -> 806
More info at: https://github.com/PyPSA/pypsa-ariadne/pull/193
=> Assume all new lines are HTLS

workflow/scripts/modify_prenetwork.py
- I already reverted the rename of EU load in main because it throws off the exporter
- @toniseibold You are multiplying domestic shipping twice by `nyears`. Is that intended? -> See my change
=> Follow up to MeOH load addtion

config/config.yaml, workflow/scripts/additional_functionality.py
With the post discretization the capacity constraints were not active for the second optimization since they already existed in `n.globalconstraints` but are not present in `n.model`.
Validation Balance Scenario
Validation Current Policies Scenario
_assertion error in `hack_transmission_grid`_
_bugfix_
=> Fix capacity constraints for post discretization

workflow/scripts/additional_functionality.py
This way we should always have the correct consttants in global constraints for all constraints and get an error if the drop does not work as expected
=> improve handling of constraints in post discretization

workflow/scripts/plot_ariadne_variables.py
according to https://energy-charts.info/charts/energy/chart.htm?l=en&c=DE&interval=year&year=2020&source=total
Industry own cosnumption is now included for e.g. gas as this it how pypsa models it. Same for coal, lignite and solar.
=> Correct electricity net generation data in validation

Changelog.md, config/config.yaml
Addressing https://github.com/PyPSA/pypsa-ariadne/issues/224
Adding a correction factor for solar to `correction_factor = 0.86` to limit the electricity generation from solar.
Modelling to target so 2020 results match the historical data.
Full load hours before PR: 1071.5
Full load hours with PR: 921.3
=> Solar Correction Factor

Changelog.md, config/config.yaml, config/scenarios.manual.yaml, workflow/scripts/export_ariadne_variables.py
Since the German government adjusted the goals for installed capacity of electrolysis units, this PR adds the boundary condition to have at least 5GW installed by 2030.
In a coarse resolution run the following development of installed capacity is observed:
=> Force 5 GW of electrolysis in Germany in 2030

.pre-commit-config.yaml, workflow/Snakefile, workflow/scripts/export_ariadne_variables.py, workflow/scripts/modify_prenetwork.py, workflow/scripts/plot_ariadne_report.py
See https://github.com/PyPSA/pypsa-eur/pull/1362
=> fix pre-commit

workflow/scripts/export_ariadne_variables.py
I accidently pushed to main, then reverted and with this PR will reapply the commit.
The changes are to conform with how negative emissions are accounted in the Ariadne database. Most importantly:
Supply side
1. DACCS and BECCS is regarded as negative emissions
2a. DACCU and BECCU are regarded as neutral
2b. BE and fossilCCS are regarded as neutral
3. fossilCCU is regarded as emissions
Demand side
4. CCU (e-fuels) is neutral
=> Conform to IAM reporting of negative emissions

Changelog.md, config/config.yaml, config/scenarios.manual.yaml
Adjusting the maximum capacity for the `CurrentPolicies` and `minus` scenarios following the [uba Projektionsbericht](https://www.umweltbundesamt.de/sites/default/files/medien/11850/publikationen/projektionen_technischer_anhang_0.pdf) Table 8:
Projected capacities 2030:
- solar: 215 GW
- onwind: 94.5 GW
- offwind: 31.3 GW
Since so far the maximum capacity of offshore wind was smaller than the report, it is also adjusted for the rest of the scenarios, hence in the `config.yaml`.
=> adjusting renewable max capacity to 'uba projektionsbericht'

config/scenarios.manual.yaml, config/scenarios.public.yaml, workflow/scripts/export_ariadne_variables.py
Since we are now seeing quite substantial network expansion in terms of Trassenlänge (exogen + endogen), we may aswell switch back to the NEP 23 costs. At least we need to do sensitivity studies. 
=> increase NEP cost assumptions again

workflow/Snakefile, workflow/scripts/export_ariadne_variables.py, workflow/scripts/plot_ariadne_variables.py
- Consider links starting with DC **as well as** TYNDP as NEP projects
- Restrict NEP projects to the current planning horizon (if they are expanded further in other planning horizons, this is accounted as endogenous)
- Change the Trassen units (see discord)
- slightly improve the NEP plots
=> improving NEP plots

config/config.yaml, workflow/Snakefile, workflow/scripts/modify_cost_data.py, workflow/scripts/modify_prenetwork.py
=> add function to scale carrier capacity

config/config.yaml, workflow/scripts/build_scenarios.py, workflow/scripts/export_ariadne_variables.py, workflow/scripts/modify_cost_data.py, workflow/scripts/modify_prenetwork.py
- add functionality to revert must run conditions if no more explicitly specified in current investment year (reason: bug)
-  do no more apply co2 price additions on fossils in 2020, 2025 (reason: co2 price in 2025 is already at around 40 €/tC02)
=> bugfix: revert must run if no more indicated

Changelog.md, config/config.yaml, workflow/scripts/build_scenarios.py, workflow/scripts/export_ariadne_variables.py, workflow/scripts/plot_ariadne_variables.py
Previously the model did not utilize waste CHPs in 2020. This PR:
- Accounts emissions from waste CHPs just like for other CHPs in the energy sector
- Sets 0 capacity for `HVC to air` in DE, because >99% of Plastikabfall are used energetically or recycled
- Set `HVC_environment_sequestration_fraction` to 0.6, which is more aligned with official statistics. 
Caveat: For Germany a more correct sequestration_fraction. would be 0.8. However, since we do not model other types of waste, we allow for a higher HVC input to waste CHPs. This way we get rough alignment with JRC-IDEES statistics on CO2  emissions from the burning of waste, as well as with the UBA statistics on energy generated from waste. For discussion and references see the comments below.
- ~~Adds a maximum capacity for the `HVC …
=> Improve waste sector

Changelog.md, config/config.yaml, workflow/Snakefile, workflow/scripts/additional_functionality.py, workflow/scripts/build_scenarios.py
This PR
- changes the source model for the aviation demand
- accounts only the domestic aviation in the national co2 target
Since the development of the aviation fuel demand in Remind seems implausible, the aviation demand factor is now calculated from the Aladin model.
Furthermore, only the domestic aviation demand is accounted to the national climate target. This is implemented by not relaxing the national emissions target in `build_scenarios` and in `additional_functionality` only accounting for the domestic aviation.
The share of domestic aviation can be obtained from multiple sources (all shares for 2019)
- manually JRC/IDEES: 7 %
- energy_totals.csv: 8.5 %
- Aladin: 7.4 % (no numbers for 2019 taking 2020 numbers)
Changes (before/after)
national CO2 targets (old) new
2020: (0.699) …
=> Adjusting Aviation Demand and Emission Accounting

Changelog.md, config/config.yaml, config/scenarios.manual.yaml, workflow/scripts/build_scenarios.py
So far little to no onshore wind is built in the South of Germany. However, this does not represent the political targets.
By forcing more onshore wind in Germany while reducing the capacity per sqkm, onshore wind is pushed into the South of Germany. Different configs were tested:
- 160 GW - 1.5 cap_per_sqkm
total potential in Germany: 242.4 GW
total installed onshore capacity 161.249 GW
- 180 GW - 1.5 cap_per_sqkm
total potential in Germany: 242.4 GW
total installed onshore capacity 180 GW
- 115 GW - 1.25 cap_per_sqkm
total potential in Germany: 202.0 GW
total installed onshore capacity 130 GW
A Flächenziel for each bus region or different regions was investigated in a [closed PR](https://github.com/PyPSA/pypsa-ariadne/pull/290) but did not lead to the desired behavior. 
The config of a …
=> Force Onshore Wind to South Germany

workflow/scripts/export_ariadne_variables.py, workflow/scripts/plot_ariadne_report.py
n.statistics.capex and .opex do not actually report CAPEX and OPEX but fixed and marginal costs. Here we compute the Capex and Opex from the overnight_cost, lifetime, discount rate and fixed costs in the post networks. In the mid-term this should all be directly available from the PyPSA Network
=> Correct reporting of CAPEX / OPEX

config/config.yaml, workflow/Snakefile, workflow/scripts/export_ariadne_variables.py, workflow/scripts/plot_ariadne_report.py, workflow/scripts/plot_ariadne_variables.py
=> correct the electricity trade calculaton

workflow/scripts/plot_ariadne_report.py
=> add second panel to regional price plot 

config/config.yaml, workflow/scripts/plot_ariadne_report.py
The report now includes a electricity balance with German title/legend/axis description, nice colors and ordered in a way that makes the plot easier to read.
caveat: the plotting does not show nice plots for a 365H run since the resampling of the data does not work properly at that temporal resolution.
Before:
After:
=> Enhance ariadne reporting

config/config.yaml
=> Adapt Kernnetz Segmentation size
