PyPSA/pypsa-ariadne

config/config.yaml

fix clustering

---

.gitignore
README.md
workflow/Snakefile
workflow/scripts/retrieve_ariadne_scenario_data.py

Like @fneum suggested, Snakemake environment variables can be used to avoid accidental commits of private usernames and passwords to the repository. Since we are working more and more with the IIASA Database it became tedious to keep adding and removing the login details from the config. With this PR you will need to add the Username and password only once to you `.bashrc`
Step 1: 
`vim ~/.bashrc`
Step 2:
at the end of the file add
```
export IIASA_USERNAME='usr'
export IIASA_PASSWORD='pwd'
```
(Insert correct usr and pwd and don't forget the quotation marks)
Step 3:
(Maybe) restart your vscode / terminal session

Use environment secrets

---

README.md

added more explanations for interactive vs code sessions @fneum

additional details on environment variables

---

config/config.yaml
workflow/scripts/modify_prenetwork.py

- Nuclear phase out in Germany by the year 2022.

added nuclear generation ban

---

workflow/Snakefile

fix rerun trigger bug due to source_path() in params for solve_sector_myopic

---

workflow/scripts/export_ariadne_variables.py

Problem formulation:
"we need to be a bit careful with the prices of hydrocarbons in the model, because they are discounted by the CO2 price of the CO2 content; to get the true prices I think you have to add CO2_price * CO2 content to the carbonaceous fuels to get the correct prices seen by consumers (e.g. add 300 EUR/tCO2 * 0.27 tCO2/MWh_fuel where first is CO2 price, second is CO2 content of fuel)"
Solution implemented in this PR. 
- CO2 price is added for gas, hard coal, lignite, oil and hydrogen. 
- fossil_fraction is calculated for the whole area, then added together with the specific CO2 emissions multiplied by the global + german CO2 price

Export prices co2

---

config/config.yaml
workflow/Snakefile
workflow/scripts/export_ariadne_variables.py

Would be nice to export at least the grid costs until end of next week

Export investments

---

workflow/Snakefile
workflow/scripts/export_ariadne_variables.py
workflow/scripts/plot_ariadne_variables.py

- export one additional Policy Varibale according to the Ariadne database: Policy|Carbon
- add plot for this carbon price
- add plot for investment variables
- add sum in plot for investment variables

add export of policy carbon price variable and plot it

---

README.md
config/config.yaml
environment.yaml
workflow/Snakefile
workflow/scripts/plot_ariadne_variables.py
workflow/scripts/retrieve_ariadne_database.py

Closes https://github.com/PyPSA/pypsa-ariadne/issues/60

update pyam package, change authentication process

---

workflow/Snakefile
workflow/scripts/plot_ariadne_scenario_comparison.py

This will make it easier to compare scenarios to each other. Just go to results/prefix/ariadne_comparison and have a look at the thumbnails, e.g.,

plot all exported variables

---

ariadne-data/costs_2019-modifications.csv
ariadne-data/costs_2020-modifications.csv
ariadne-data/costs_2025-modifications.csv
ariadne-data/costs_2030-modifications.csv
ariadne-data/costs_2035-modifications.csv
ariadne-data/costs_2040-modifications.csv
ariadne-data/costs_2045-modifications.csv
ariadne-data/costs_2050-modifications.csv

Just changing the distribution grid costs from ~3000€/kW to 1500€/kW based on Tom's expert opinion.

Changing distribution grid costs

---

workflow/Snakefile
workflow/scripts/plot_ariadne_variables.py

adds 
to the ariadne output folder

add electricity validation plot for 2020

---

config/config.yaml
workflow/Snakefile
workflow/scripts/modify_prenetwork.py

quick fix for our biomass problems:
- biomass plants are mistakenly added as solid biomass and not biogas 
- share of biomass in electricity generation is very low
A must run condition with p_min_pu of 0.7 leads to following results (365H):
before:
after:
before:
after:

must run condition for biomass

---

config/scenarios.manual.yaml
workflow/Snakefile
workflow/scripts/build_scenarios.py

supersedes #91 
-> renaming of functions and variables
-> slightly different code structure
-> increased 2020 target
-> specified the scenarios which keep the KSG targets
-> took all targets from the Appendix of the UBA Projektionsbericht

add option for UBA target, rename functions and variables

---

config/config.yaml
workflow/Snakefile
workflow/scripts/export_ariadne_variables.py
workflow/scripts/plot_ariadne_variables.py

Add missing variables:
for trade:
<google-sheets-html-origin><style type="text/css"></style>
2 | energy (supply) | Trade\|Primary Energy\|Biomass\|Volume | xx | not modelled | PJ/yr | net exports of solid, unprocessed biomass, at the global level these should add up to the trade losses only
-- | -- | -- | -- | -- | -- | --
2 | energy (supply) | Trade\|Secondary Energy\|Electricity\|Volume | xx | added  | PJ/yr | net exports of electricity, at the global level these should add up to the trade losses only
2 | energy (supply) | Trade\|Secondary Energy\|Hydrogen\|Volume | xx |  added | PJ/yr | net exports of hydrogen, at the global level these should add up to the trade losses only
2 | energy (supply) | Trade\|Secondary Energy\|Liquids\|Hydrogen\|Volume | xx | not modelled? | PJ/yr | net …

Export missing variables for trade and policy

---

workflow/scripts/additional_functionality.py

config constraints:
outcome: 
trade plot:

fix bug in electricity imports constraint

---

workflow/scripts/export_ariadne_variables.py

add functionality to derive imports and exports and plot them

---

workflow/scripts/modify_prenetwork.py

Factor for Vehicle2Grid link, BEV_charger and Demand Side Management was not applied due to non matching indices.

Bugfixing Transport Sector from Aladin

---

config/config.yaml
workflow/Snakefile
workflow/scripts/export_ariadne_variables.py
workflow/scripts/modify_prenetwork.py
workflow/scripts/plot_ariadne_variables.py

Needs https://github.com/PyPSA/PyPSA/pull/989 and https://github.com/PyPSA/pypsa-eur/pull/1156

Investment exports

---

.github/workflows/validate.yml
config/config.yaml

Include spain

---

.github/workflows/validate.yml
config/config.yaml

- use newest version of validator (https://github.com/lkstrp/pypsa-validator)
- pin version instead of main branch
- use single job for artifact uploads
- fixes plots path

ci: adjust ci to new validator

---

config/config.yaml
config/scenarios.manual.yaml
workflow/scripts/additional_functionality.py

As stated in the [ToDos](https://docs.google.com/document/d/1ZVNe4JPoPZsUgI_-1NLt8aY1ML8CsBFoRpInAtg31ts/edit#heading=h.x5lqayz7xa9), the NEP 2021 costs are now assumed for all scenarios except for the two worst case scenarios.
Furthermore, following the discussion on [discord](https://discord.com/channels/914472852571426846/1148559814381805588/1283395045336027159), the potential for renwables in Germany are set as the following:
- PV: 1000 GW
- Onshore Wind: 250 GW
- Offshore Wind: 70 GW
Those new limits come into effect as soon as the legislature gives no certain capacity goals anymore.
In `additional_functionality` the constraints were only added to the linopy model which does not allow to look into them in the postnetwork. I added the constraints to the pypsa model as wel.
Before …

Config Adjustments

---

config/config.yaml
config/scenarios.manual.yaml
workflow/scripts/export_ariadne_variables.py
workflow/scripts/modify_prenetwork.py

make targets a little less ambitious

---

config/config.yaml
workflow/scripts/additional_functionality.py
workflow/scripts/plot_ariadne_variables.py

- add net electricity to validation and restrict nuclear electricity generation

Update and improve elec validation in 2020

---

config/config.yaml
workflow/Snakefile
workflow/scripts/export_ariadne_variables.py
workflow/scripts/modify_prenetwork.py

add methanol links

---

config/config.yaml
workflow/Snakefile
workflow/scripts/build_existing_chp_de.py

Master into ariadne2 october

---

config/config.yaml
workflow/Snakefile

watch pypsa-eur data folder for changes

---

config/config.yaml
workflow/Snakefile
workflow/scripts/plot_ariadne_report.py

plotting routine for Szenarienreport

---

config/config.yaml
environment.yaml
workflow/scripts/export_ariadne_variables.py
workflow/scripts/modify_prenetwork.py

update to pypsa 0.31.0

---

workflow/scripts/modify_prenetwork.py

Fix: Disallow expansion of dummy Offshore NEP generator

---

config/config.yaml
workflow/scripts/export_ariadne_variables.py

add green h2 to exporter, include methanol in price for liquids from h2

---

config/config.yaml
workflow/scripts/export_ariadne_variables.py
workflow/scripts/modify_prenetwork.py

Related PR: https://github.com/PyPSA/pypsa-eur/pull/1391

add compression losses for gas transport

---

workflow/Snakefile
workflow/scripts/export_ariadne_variables.py
workflow/scripts/plot_ariadne_variables.py

Based on Tom's calculation of Investment components in NEP. Work in progress.

Reactive power compensation and NEP plots

---

config/config.yaml
workflow/Snakefile
workflow/scripts/export_ariadne_variables.py
workflow/scripts/plot_ariadne_report.py

plot heat timeseries

---

config/config.yaml
config/scenarios.manual.yaml
workflow/scripts/export_ariadne_variables.py

update co2 targets  with EEA historical values and projections

---

workflow/scripts/export_ariadne_variables.py

post-discretize the projects in the hacking function to unify later code

---

config/scenarios.manual.yaml

remove impossible onshore wind constraint

---

config/config.yaml
workflow/scripts/plot_ariadne_report.py

change plot titles to german

---

config/config.yaml

upstream: bugfix: correct co2 intensity of unsustainable bioliquids

---

config/config.yaml
workflow/Snakefile
workflow/scripts/build_wasserstoff_kernnetz.py
workflow/scripts/cluster_wasserstoff_kernnetz.py
workflow/scripts/export_ariadne_variables.py
workflow/scripts/modify_prenetwork.py
workflow/scripts/plot_ariadne_variables.py

calc Kernnetz invest and plot it

---

workflow/Snakefile
workflow/scripts/export_ariadne_variables.py

Improve district heat accounting

---

workflow/scripts/export_ariadne_variables.py

add total system cost to exporter

---

ariadne-data/costs_2019-modifications.csv
ariadne-data/costs_2020-modifications.csv
ariadne-data/costs_2025-modifications.csv
ariadne-data/costs_2030-modifications.csv
ariadne-data/costs_2035-modifications.csv
ariadne-data/costs_2040-modifications.csv
ariadne-data/costs_2045-modifications.csv
ariadne-data/costs_2050-modifications.csv

Add Source to Electricity Distribution Grid Investments

---

config/config.yaml
workflow/scripts/plot_ariadne_report.py

Adding the following plots to the plotting routine:
- electricity import/export
- hydrogen import/export
- installed capacities Germany
- updated storage plot (for Germany only)

Even More Plots For Ariadne Report

---

workflow/scripts/export_ariadne_variables.py
workflow/scripts/plot_ariadne_report.py

general update of report plots

---

config/config.yaml

Duplicate of https://github.com/PyPSA/pypsa-ariadne/pull/304
I had to force push, because this PR needs to be merge a bit later

increase kernnetz segmentation size

---

README.md

Add deprecated warning and link to new repo
